server:
  port: 7080

spring.application:
  name: api-gw

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761:eureka/

spring.cloud:
  gateway:
    httpclient:
      connect-timeout: 3000
      response-timeout: 10s
#    default-filters:
#      - name: GlobalFilter
#        args:
#          defaultMessage: Api Gateway
#          preLogger: true
#          postLogger: true
    routes: # ??? ??? api ????
      - id: post-service
        uri: http://localhost:8080/
        predicates:
          - Path=/v1.0/contents/**
      - id: time-service
        uri: http://localhost:8080
        predicates:
          - Path=/v1.0/newservice
          - After=2024-08-25T14:00:00.126+09:00[Asia/Seoul]

